version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: 'America/Montreal'
    # Disable rebasing for npm pull requests
    rebase-strategy: 'disabled'
    open-pull-requests-limit: 0
