name: Botpress CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/botpress:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/botpress:${{ github.sha }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/botpress:${{ github.sha }}
